globalVariables(c("value",
                    "variable",
                    "yend",
                    "xend",
                    "row_id",
                    "x",
                    "y",
                    "y.x",
                    "y.y"))
